{{- if and .Values.token.value (not .Values.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "yarad.fullname" .) }}
  labels:
    {{- include "yarad.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.token.secretKey }}: {{ .Values.token.value | quote }}
{{- end }}
{{- if and .Values.abuseChKey.value (not .Values.abuseChKey.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-abusech" (include "yarad.fullname" .) }}
  labels:
    {{- include "yarad.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.abuseChKey.secretKey }}: {{ .Values.abuseChKey.value | quote }}
{{- end }}
